community_name: "The Last Bunker"
community_tagline: "The Last Bunker"
community_description:  "The Best Place for People Who Love Fallen Earth"
support_email:  "admin@panthersoftware.com"
meta_description: 'A Fallen Earth Fansite'
meta_keywords: 'Fallen Earth, MMORPG'
sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']

# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "en"

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)

# min and max age for users to use the site
min_age: 16
max_age: 190

photo:
  missing_thumb: '/images/icon_missing_thumb.gif'
  missing_medium: "/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "100x100c", medium: "290x320c", large: "664>"}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

#closed_beta_mode: true

#require_captcha_on_signup: false
allow_anonymous_commenting: true
recaptcha_pub_key: PUB KEY
recaptcha_priv_key: PRI KEY
